Apply feedback
shanemachine92/web_TTT pull request #3
Opened 2017-07-28 23:27 UTC by shanemachine92

Fixed all of the styling issues, wrote tests, added win_check helper method, and fixed cell overwrite bug

2017-07-29 04:05 UTC, cbnoonan requested changes

2017-07-29 04:05 UTC, cbnoonan commented on lib/app.rb
> +  post '/set_cell' do
this looks exactly like app.rb  why do we need two files that do the same thing?

2017-07-29 04:05 UTC, cbnoonan commented on lib/game.rb
> +attr_accessor :player1, :player2, :board, :current_player, :total_moves, :message, :game_over
probably want to indent this line

2017-07-29 04:05 UTC, cbnoonan commented on lib/game.rb
> +      if @board.cell_empty?(cell)
4 space indent and then 2 space indent.  You want to have consistency.

2017-07-29 04:23 UTC, shanemachine92 commented on lib/app.rb
> +  post '/set_cell' do
That's weird, lib/app.rb should have been deleted. Dupe file.

2017-08-04 23:38 UTC, JesseBuesking approved these changes
Just some pointers/comments, no changes required.

2017-08-04 23:38 UTC, JesseBuesking commented on lib/board.rb
> +    return true if win?(piece)
Could just be `win?(piece)`

2017-08-04 23:38 UTC, JesseBuesking commented on lib/board.rb
> +    !(x).empty? && x == y && y == z
Can probably do `x.present? && x == y && y == z`

2017-08-04 23:38 UTC, JesseBuesking commented on lib/board.rb
> +    if win_helper(@cells[:one], @cells[:two], @cells[:three]) ||
Can just keep the conditional. It will resolve to `true` or `false` itself.

2017-08-04 23:38 UTC, JesseBuesking commented on lib/game.rb
> +    if @board.game_won?(piece)
This could be `@game_over = @total_moves == 9 || @board.game_won?(piece)`

2017-08-09 05:05 UTC, ryanabooth requested changes
I think the win checker might could use some help:
<img width="629" alt="screen shot 2017-08-08 at 10 04 02 pm" src="https://user-images.githubusercontent.com/1295846/29105838-97cab2e6-7c85-11e7-8cdc-c634164eff75.png">

And you can keep playing after a win (hacks!) 😏
![not finished yet](https://user-images.githubusercontent.com/1295846/29105847-ae6f345e-7c85-11e7-8470-9a0d637891e1.gif)

2017-08-09 05:06 UTC, ryanabooth commented
Sorry I was so late to the party Shane. 😃

2017-08-14 03:08 UTC, cbnoonan commented on lib/board.rb
> +    !(x).empty? && x == y && y == z
I would recommend this change. :)

2017-08-15 18:10 UTC, shanemachine92 commented on lib/board.rb
> +    !(x).empty? && x == y && y == z
This change broke the game!

2017-08-15 18:18 UTC, shanemachine92 commented
@ryanabooth fixed! Good eye, the lost fix for that is in the latest commit.

2017-08-16 21:00 UTC, JesseBuesking commented on lib/board.rb
> +    !(x).empty? && x == y && y == z
Why did it break the game?

2017-08-16 21:01 UTC, JesseBuesking reviewed
Left a question inline.

2017-08-16 22:40 UTC, shanemachine92 commented on lib/board.rb
> +    !(x).empty? && x == y && y == z
@JesseBuesking 
```  def win_helper(x, y, z)
    x.present? && x == y && y == z
  end```

resulted in the following error:

```NoMethodError - undefined method `present?' for "M":String
Did you mean?  prepend:
	/Users/shane/work/JSON_MvT/lib/board.rb:25:in `win_helper'
	/Users/shane/work/JSON_MvT/lib/board.rb:29:in `win?'
	/Users/shane/work/JSON_MvT/lib/board.rb:21:in `game_won?'
	/Users/shane/work/JSON_MvT/lib/game.rb:32:in `play_game'
	app.rb:29:in `block in <main>'```

2017-08-16 23:01 UTC, shanemachine92 commented on lib/board.rb
> +    !(x).empty? && x == y && y == z
It's a rails method and I'm using Sinatra. Tried installing and requiring active support, but still breaking. 

https://stackoverflow.com/questions/18810562/how-to-use-ruby-method-present

I can keep trying if it feels like an important change.

2017-08-17 03:54 UTC, cbnoonan commented on lib/board.rb
> +    !(x).empty? && x == y && y == z
it's not a hugely important change, but it is good to know how to use bits and pieces from Rails if you need to. I'm curious what error you received when trying to include ActiveSupport?

2017-08-17 16:01 UTC, shanemachine92 commented on lib/board.rb
> +    !(x).empty? && x == y && y == z
Same error as above :/

2018-03-13 20:16 UTC, closed without merging